/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  access_token: string | null;
  expires_at: Int8 | null;
  id: Generated<number>;
  id_token: string | null;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  userId: number;
}

export interface Articles {
  date_created: Generated<Timestamp | null>;
  date_written: Timestamp | null;
  id: Generated<number>;
  source: string;
  text: string;
  user_id: number | null;
}

export interface Media {
  article_id: number;
  date_created: Generated<Timestamp | null>;
  id: Generated<number>;
  media_type: string;
  media_url: string;
  prompt: string | null;
  style: string | null;
}

export interface Posts {
  caption: string | null;
  id: Generated<number>;
  media_id: number;
  posted_at: Timestamp | null;
  scheduled_at: Timestamp;
  social_account_id: number;
}

export interface Sessions {
  expires: Timestamp;
  id: Generated<number>;
  sessionToken: string;
  userId: number;
}

export interface Socials {
  access_token: string;
  account_identifier: string;
  expires_at: Timestamp | null;
  id: Generated<number>;
  provider: string;
  refresh_token: string | null;
  user_id: number;
}

export interface Users {
  credits: number | null;
  email: string | null;
  emailVerified: Timestamp | null;
  id: Generated<number>;
  image: string | null;
  name: string | null;
  stripeCustomerId: string | null;
}

export interface VerificationToken {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface CreditPurchases {
  amount: number;
  credits: number;
  id: Generated<number>;
  status: string;
  stripe_payment_intent_id: string;
  stripe_session_id: string;
  user_id: number;
}

export interface Subscriptions {
  id: Generated<number>;
  status: string;
  stripe_current_period_end: Timestamp;
  stripe_price_id: string;
  stripe_subscription_id: string;
  updated_at: Timestamp | null;
  user_id: number;
}

export interface DB {
  accounts: Accounts;
  articles: Articles;
  credit_purchases: CreditPurchases;
  media: Media;
  posts: Posts;
  sessions: Sessions;
  socials: Socials;
  subscriptions: Subscriptions;
  users: Users;
  verification_token: VerificationToken;
}
